.eslintignore
.eslintrc.json
package.json
src/App.tsx
src/index.tsx
src/pages/CreateDesign/Detail/index.tsx
src/pages/CreateDesign/Pattern/index.tsx
src/pages/CreateDesign/Review/index.tsx
src/pages/CreateDesign/index.tsx
src/pages/Designs/index.tsx
src/pages/Error404/index.tsx
src/pages/index.tsx
tsconfig.json
yarn.lock

초기 `router`를 세팅합니다
변경 사항
- `import/order`를 설정했습니다.
- `tsconfig` `baseUrl`을 `./src`로 설정했습니다.
- 라우터를 위한 패키지를 추가했습니다.
- `query-string`, `react-router-dom`, `use-query-params` 패키지
-  `.eslintignore` 파일 추가했습니다.
- 초기 라우터 세팅을 했습니다.
- `Error404` 페이지
- `NewDesign/Detail`, `NewDesign/Pattern`, `NewDesign/Review` 페이지
Resolve #3

[Feat] 초기 router 세팅

---

.eslintrc.json
src/App.tsx
src/dumbs/Button/index.tsx
src/pages/CreateDesign/components/Container/index.tsx
src/pages/CreateDesign/components/Footer/index.tsx
src/pages/CreateDesign/components/Header/index.tsx
src/pages/CreateDesign/index.tsx
src/pages/CreateDesign/recoils.ts
src/pages/CreateDesign/types.ts

Resolve #2 새로운 도안 작성하기 - 프레임 구현
모각코한 작업물까지 먼저 올립니다.
새로운 도안 작성하기 기능의 기본 프레임을 구현합니다. (프로그래스바는 후속 이슈로..)
- step 별 알맞게 컨텐츠 랜더링
- Header 추가
- 페이지 설명 
- Footer 추가
- step 별 버튼
코드 리뷰만 받고 디자인 리뷰 같은 건 프로그래스바 하면서 같이 반영할게요!

[Feat] 새로운 도안 작성하기 - 프레임 구현

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Fix #17 
name, about, title, labels, assignees가 없어서 그런 것은 아닐까 해서 넣어서 pr을 올려봅니다

[Fix] 이슈 추가 시 이슈 템플릿이 나올 수 있도록 수정

---

src/pages/CreateDesign/components/Header/index.tsx
src/pages/CreateDesign/components/StepProgressBar/index.tsx
src/pages/CreateDesign/types.ts

Resolve #9 새로운 도안 작성하기 - 프로그래스바 구현
현재 위치한 페이지 단계를 보여주는 프로그래스바 구현
스타일 주는 방법 통일해야 하는데....... (먼산)
- material 의 Step 컴포넌트를 써서 애니메이션은 구현하지 않았습니다.
- https://github.com/k-roffle/knitting-frontend/pull/8 에서 받은 스타일, 컴포넌트 분리는 후속 이슈로 다룹니다.

[Feat] 새로운 도안 작성하기 - 프로그래스바 구현

---

src/pages/CreateDesign/index.tsx
src/themes/index.ts
src/themes/overrides.ts
src/themes/palatte.ts
src/themes/typography.ts

Close #12 
#14 을 베이스로 작업했습니다
[Feat: Mui palette를 오버라이딩하는 palette 파일 추가](https://github.com/k-roffle/knitting-frontend/commit/3e9110550ce89a24d68ee7f1b531ccf1abbd9f75)부터 봐주세요
- Mui palette를 오버라이딩하는 palette 파일을 추가했습니다
- Mui typography를 오버라이딩하는 typography 파일을 추가했습니다
- Mui 컴포넌트를 오버라이딩하는 overrides 파일을 추가했습니다
- CreateDesign 페이지에 오버라딩한 theme를 적용했습니다

[Feat] 공통으로 쓰이는 글로벌 테마 정의

---

src/dumbs/Button/index.tsx
src/pages/CreateDesign/components/StepProgressBar/index.tsx
src/themes/index.ts
src/themes/overrides.ts
src/themes/zIndex.ts

Close #13 
스타일 주입 방법 리팩토링
- 버튼 테마 정의: https://github.com/k-roffle/knitting-frontend/pull/15#discussion_r597658396 리뷰 반영 -> primary만 적용해 주면 돼서 스타일을 추가로 정의하지는 않았습니다.
- 스타일과 컴포넌트 분리: https://github.com/k-roffle/knitting-frontend/pull/8#discussion_r593912079 리뷰 반영
- 스타일 컴포넌트로 변경: https://github.com/k-roffle/knitting-frontend/pull/11#discussion_r596827460 리뷰 반영
- z-index 별도로 정의: https://github.com/k-roffle/knitting-frontend/pull/11#discussion_r596824251 리뷰 반영

[Refactor] 스타일 주입 방법 리팩토링

---

.env
package.json
src/pages/CreateDesign/components/Footer/index.tsx
src/utils/config.ts
src/utils/requests.ts
yarn.lock

Close #30
- SERVER_URL 변경
- API 호출 인터페이스 셋팅
https://github.com/k-roffle/word-way-frontend/blob/main/src/utils/requests.ts 이 코드를 참고했습니다~ 🙏 
x
x

[Feat] 서버 API 호출 인터페이스 셋팅

---

src/pages/CreateDesign/Pattern/constants.ts
src/pages/CreateDesign/Pattern/index.tsx
src/pages/CreateDesign/Pattern/types.ts
src/pages/CreateDesign/Pattern/utils.ts
src/pages/CreateDesign/components/Footer/index.tsx
src/utils/errors.ts

pattern 최대 길이를 지정하지 않으면 많이 입력했을 때 렌더링 이슈가 있기 때문에 최대 길이를 지정합니다
Close #59 
- pattern 최대 길이를 3000자로 지정했습니다
- Snackbar 에러 메시지를 상수로 정의하도록 했습니다
- 마진을 상위에서 주도록 했습니다
- 3000자가 넘는 상태에서 붙여넣기를 하면 토스트가 나타납니다

[Feat] pattern 최대 길이 지정

---

src/routers/DesignRouter/index.tsx
src/routers/LoginRouter/index.tsx
src/utils/auth.ts
src/utils/route.tsx

Resolves: #66 
- 토큰이 없는 경우 로그인 화면으로 리다이렉트 하는 라우터 구현
- 도안 생성 페이지에 ProtectedRouter 적용 
- 로그인한 사용자는 로그인한 페이지에 접근할 수 없도록
- 다른 엣지 케이스는 없을지 🤔

Feat: 로그인한 사용자만 접근할 수 있는 Router 구현

---

package.json
src/utils/auth.ts
yarn.lock

토큰이 거의 만료되어갈 때 리프레시 해올 수 있도록 구현
resolves: #51 
- access token을 가져올 때 만료시간 확인 후 1시간 미만 남은 경우 리프레시
- async 요청이 적절한지 :eyes:

Feat: 토큰이 거의 만료되어갈 때 리프레시 해올 수 있도록 구현

---

.env

배포된 서버와 통신할 수 있도록 서버주소를 변경합니다.
- 환경 변수 변경

Feat: 서버 주소를 업데이트 합니다.

---

src/components/Footer/index.tsx
src/components/Header/index.tsx
src/components/index.ts
src/dumbs/Layout/index.tsx
src/dumbs/Logo/index.tsx
src/dumbs/RequiredSelect/index.tsx
src/dumbs/index.tsx
src/pages/CreateDesign/Detail/index.tsx
src/pages/CreateDesign/Pattern/index.tsx
src/pages/CreateDesign/components/Footer/index.tsx
src/pages/CreateDesign/components/Header/index.tsx
src/pages/CreateDesign/components/StepProgressBar/index.tsx
src/pages/CreateDesign/index.tsx
src/pages/Login/index.tsx
src/plugins/unitDecorator/unitDecorator.tsx
src/themes/overrides.ts

Resolve #72 
- Header와 Footer 컴포넌트를 추가합니다

[Design] Header와 Footer 컴포넌트 추가

---

src/pages/CreateDesign/Detail/index.tsx
src/pages/CreateDesign/components/Footer/index.tsx
src/pages/CreateDesign/recoils.ts
src/pages/CreateDesign/types.ts
src/plugins/unitDecorator/unitDecorator.tsx
src/utils/auth.ts

도안 생성 API 요청이 정상적으로 이뤄지도록 수정합니다.
resolves: #82, #75
- Authorization Header에 token 추가
- request body 수정
- yarn 필드 필수값으로 수정

fix: 도안 생성 API 요청이 정상적으로 이뤄지도록 수정

---

src/pages/LoginRedirected/index.tsx

Resolve #79 
- CircularProgress 컴포넌트 중앙정렬 하도록 수정합니디

[Design] CircularProgress 컴포넌트 중앙정렬 하도록

---

src/pages/LoginRedirected/index.tsx
src/utils/auth.ts

API 응답 spec이 변경된 것을 반영합니다.
응답을 받아 처리하는 부분을 수정해주었습니다.
resolves: #86
- 응답 받아 처리하는 부분 수정
- 도안 생성시 추가된 필드들이 있는데 이건 프론트 작업이 필요하고 @YuuRiLee 가 진행하기로 해서 별도로 진행하지 않았습니다.
- 즉 현재 클라이언트로 도안 생성이 불가능한 상태입니다.
- 로그인 쪽 외에는 요청하는게 없던데 맞나요? 🤔

feat: API 응답 스펙 변경 적용

---

.eslintrc.json
package.json
src/components/CommonSnackbar/useCommonSnackbar.ts
src/constants/errors.ts
src/dumbs/Skeleton/index.tsx
src/pages/MyInformation/components/DesignItem/index.tsx
src/pages/MyInformation/components/Designs/index.tsx
src/pages/MyInformation/components/InformationTabs/index.tsx
src/pages/MyInformation/hooks/types.ts
src/pages/MyInformation/hooks/useGetMyDesigns.ts
src/utils/requestType.ts
yarn.lock

#81
- SWR 패키지를 추가합니다
- eslint camelcase 옵션을 끕니다
- loading일 경우 스켈레톤이 나오게 designItem을 수정합니다
- 내 도안 목록을 가져오는 useGetMyDesigns 훅을 추가합니다
- 내 도안 리스트 api 연결을 합니다

[Feat] 내 도안 리스트 서버 연결

---

package.json
src/pages/MyInformation/components/DesignItem/index.tsx
src/pages/MyInformation/hooks/types.ts
src/utils/format.ts
yarn.lock

[Feat] design item에 date 정보 보여줄 수 있도록 수정

---

src/pages/CreateDesign/components/Footer/index.tsx
src/pages/MyInformation/hooks/useGetMyDesigns.ts
src/utils/auth.ts
src/utils/errors.ts
src/utils/requests.ts

Resolve #96
- Error를 관리하는 util 파일 추가
- request useCurrentToken을 true로 하면 getAccessToken에서 가져온 토큰을 사용하도록

[Refactor] request - accessToken 넘겨주지 말고 boolean 값으로 토큰 사용할지 판단하도록 

---

src/components/Ellipsis/index.tsx
src/pages/Login/index.tsx
src/utils/auth.ts

- 계속 로그인으로 리다이렉트하는 문제 수정
- 불필요한 window 삭제

#117 계속 로그인으로 리다이렉트하는 문제 수정

---

src/pages/CreateDesign/components/Footer/index.tsx
src/pages/CreateProduct/SelectDesigns/index.tsx
src/pages/MyInformation/components/DesignItem/DesignItem.css.ts
src/pages/MyInformation/components/DesignItem/index.tsx
src/pages/MyInformation/hooks/types.ts
yarn.lock

Resolve #122
- 내 도안 리스트 컴포넌트에 체크 박스로 선택할 수 있도록합니다
- DesignItem 스타일 관련 코드들을 분리합니다

[Feat] 판매할 도안 리스트 체크박스 추가

---

src/constants/errors.ts
src/pages/CreateDesign/components/Footer/index.tsx
src/pages/MyInformation/components/MyProfile/MyProfile.css.ts
src/pages/MyInformation/components/MyProfile/index.tsx
src/pages/MyInformation/hooks/types.ts
src/pages/MyInformation/hooks/useGetMyProfile.ts
src/pages/MyInformation/hooks/useGetMySalesSummary.ts
src/utils/requestType.ts

Resolve #105 
- `/me/profile` api 연동
- error로 떨어지겠지만 리턴 data가 null || undefined 일 때 핸들링
- 프로필 이미지 사이즈 규격화 되어있는지 ?
- `useRenderEmptyContent`로 `EmptyContent` 데이터 내려주고 있는데 이것도 규모가 커질 것 같아서 분리단위 (?) 이야기해보면 좋겠습니다. @YuuRiLee

Feat: 내 프로필 불러오기 api 연동

---

src/dumbs/InlineInput/index.tsx
src/pages/CreateProduct/Package/index.tsx

상품 생성 시 할인가보다 정가가 작은 경우 에러 메시지를 노출하도록 합니다.
> sprint-2-4 브랜치가 main에 병합돼서 main에서 따서 작업하고 main으로 PR 올렸어요!  
혹시 다른 브랜치로 병합되어야 할까유?
f739b46 커밋은 아래 콘솔 오류를 수정한 내역입니다 !
```
Warning: React does not recognize the `isInvalid` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isinvalid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

[Feat] 상품 생성 시 정가, 할인가 validate

---

src/pages/CreateProduct/types.ts
src/pages/MyInformation/components/DesignItem/DesignItem.css.ts
src/pages/MyInformation/components/DesignItem/index.tsx
src/themes/palette.ts

Resolve #[2dmzvnz](https://app.clickup.com/t/2dmzvnz)
- ThemeProvider 사용하도록 수정
- 도안카드 스타일 수정
- 도안 카드의 가격은 아직 피그마 디자인 파일에 없어서 추후 스프린트에서 수정될 것 같습니다.
[피그마 디자인 파일]
[AS-IS]
[TO-BE]

[Feat] 도안 카드 컴포넌트 수정

---

src/pages/MyInformation/components/DesignItem/DesignItem.css.ts
src/pages/MyInformation/components/DesignItem/index.tsx

[Click Up 이슈 링크](https://app.clickup.com/t/2fz7zpf)
- 도안 아이템 햄버거 메뉴 클릭 시 도안 수정 기능 추가

[Feat] 도안 아이템 햄버거 메뉴 추가

---

src/dumbs/Button/index.tsx
src/dumbs/Modal/Modal.css.ts
src/dumbs/Modal/index.tsx
src/pages/CreateDesign/Review/index.tsx
src/pages/CreateDesign/atom.ts
src/pages/CreateProduct/components/Footer/hooks/useSaveProduct.ts
src/pages/CreateProduct/components/Footer/index.tsx
src/pages/CreateProduct/components/StepProgressBar/index.tsx
src/pages/CreateProduct/hooks/useGetStepContents.ts
src/pages/CreateProduct/index.tsx
src/pages/CreateProduct/recoils.ts

[Click Up 이슈 링크](https://app.clickup.com/t/2fz7zmc)
- 도안 생성 마지막 단계에서 모달을 노출합니다.
- 
- `/dumbs` 하위에 모달 컴포넌트 생성(`Modal/index.tsx`)

[Feat] 도안 저장 버튼 누를 시 도안 저장 완료 모달 띄우기

---

src/pages/MyInformation/components/InformationTabs/index.tsx
src/pages/MyInformation/components/MyProfile/MyProfile.css.ts
src/pages/MyInformation/components/Products/index.tsx

[Click Up 이슈 링크](https://app.clickup.com/t/2fz7zpa)
- `/my` 페이지에서 판매중인 상품 탭을 활성화
- 판매중인 상품 탭 선택 시 보이는 컴포넌트 추가

[Feat] 판매중인 상품 리스트 컴포넌트 추가

---

src/dumbs/InputWithLabel/index.tsx
src/pages/EditDesign/atom.ts
src/pages/EditDesign/components/Footer/hooks/useSaveDesign.ts
src/pages/EditDesign/types.ts
src/pages/MyInformation/components/InformationTabs/useRenderEmptyContent.ts
src/pages/MyInformation/components/MyProfile/index.tsx

[Feat] 2-3 상품 판매 등록하기

---

src/dumbs/Modal/Modal.css.ts
src/dumbs/Modal/index.tsx
src/pages/CreateProduct/components/Footer/hooks/useSaveProduct.ts
src/pages/CreateProduct/components/Footer/index.tsx
src/pages/CreateProduct/components/StepProgressBar/index.tsx
src/pages/CreateProduct/hooks/useGetStepContents.ts
src/pages/CreateProduct/index.tsx
src/pages/CreateProduct/recoils.ts
src/pages/EditDesign/Cover/index.tsx
src/pages/EditDesign/Outline/index.tsx
src/pages/EditDesign/Review/index.tsx
src/pages/EditDesign/atom.ts
src/pages/MyInformation/components/CountIcon/CountIcon.css.ts
src/pages/MyInformation/components/CountIcon/index.tsx
src/pages/MyInformation/components/DesignItem/DesignItem.css.ts
src/pages/MyInformation/components/DesignItem/index.tsx
src/pages/MyInformation/components/InformationTabs/InformationTabs.css.ts
src/pages/MyInformation/components/InformationTabs/index.tsx
src/pages/MyInformation/components/MyProfile/index.tsx
src/pages/MyInformation/hooks/useMySummary.ts
src/pages/MyInformation/types.ts
src/themes/palette.ts

[Click Up 이슈 링크](https://app.clickup.com/t/)

[Feat] 2-4 도안 작성 페이지 디벨롭 스프린트 정리

---

.github/workflows/build_and_deploy.yml

[Click Up 이슈 링크](https://app.clickup.com/t/)

[Chore] build fail 나는 step 수정

---

src/App.tsx

[Click Up 이슈 링크](https://app.clickup.com/t/)
- 초기 접속 페이지 설정 
- 로그인 시: 내 정보
- 비로그인 시: 로그인)

[Feat] 초기 라우터 페이지 변경

---

.github/workflows/build_and_deploy.yml

[Click Up 이슈 링크](https://app.clickup.com/t/)

[Chore] main 브랜치 병합시에만 hosting 되도록 설정

---

src/App.tsx
src/components/Header/index.tsx
src/constants/path.ts
src/dumbs/Logo/index.tsx
src/dumbs/Modal/index.tsx
src/pages/CreateProduct/Confirm/index.tsx
src/pages/CreateProduct/SelectDesigns/index.tsx
src/pages/CreateProduct/components/Footer/hooks/useProduct.ts
src/pages/CreateProduct/components/Footer/index.tsx
src/pages/CreateProduct/recoils.ts
src/routers/MyInformationRouter/index.tsx
src/routers/ProductRouter/index.tsx
src/routers/index.tsx

[Fix] 여러 자잘한 버그 수정

---

src/pages/MyInformation/components/DesignItem/DesignItem.css.ts

- 이미지 컴포넌트에 shadow 추가
[before]
[after]
Resolve #179

[Feat] 이미지 컴포넌트 shadow 추가
